CREATE VIEW ALL_ALBUMS(ALBUM_ID, TITLE, PLAYTIME, GENRE, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE, ALBUM_TYPE) AS
SELECT ALBUM_ID, TITLE, PLAYTIME, GENRE, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE, 'VINYL' ALBUM_TYPE FROM VINYL
UNION ALL
SELECT ALBUM_ID, TITLE, PLAYTIME, GENRE, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE, 'TAPE' FROM TAPE
UNION ALL
SELECT ALBUM_ID, TITLE, PLAYTIME, GENRE, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE, 'CD' FROM CD
UNION ALL
SELECT ALBUM_ID, TITLE, PLAYTIME, GENRE, RELEASE_DATE, TRACK, REVIEWS, NULL, PRICE, 'MP3' FROM MP3;
