SELECT ALBUM_ID, TITLE, PLAYTIME, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE FROM VINYL
UNION
SELECT ALBUM_ID, TITLE, PLAYTIME, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE FROM TAPE
UNION
SELECT ALBUM_ID, TITLE, PLAYTIME, RELEASE_DATE, TRACK, REVIEWS, NEW_OR_USED, PRICE FROM CD
UNION
SELECT ALBUM_ID, TITLE, PLAYTIME, RELEASE_DATE, TRACK, REVIEWS, NULL, PRICE FROM MP3;
