INSERT INTO ALBUM VALUES(CD_TYPE(1,'Tchaikovsky: Swan Lake (Complete Ballet)(DISC1)', 180, 'Classical', TO_DATE('01/06/2004', 'DD/MM/RRRR'),
TRACKS(TRACK_TYPE(1,'Introduction: Moderato Assai - Allegro Ma Non Troppo',180,0.99),
TRACK_TYPE(2,'No.1 - Scene: Allegro Giusto',180,0.99),
TRACK_TYPE(3,'No.2 - Valse: Tempo Di Valse',180,0.99),
TRACK_TYPE(4,'No.3 - Scene: Allegro Moderato',180,0.99),
TRACK_TYPE(5,'I: Intrada: Allegro',180,0.99),
TRACK_TYPE(6,'I: Intrada: Allegro',180,0.99),
TRACK_TYPE(7,'III: Allegro Semplice',180,0.99),
TRACK_TYPE(8,'IV: Moderato',180,0.99),
TRACK_TYPE(9,'V: Allegro',180,0.99),
TRACK_TYPE(10,'VI: Coda: Allegro Vivaceo',180,0.99),
TRACK_TYPE(11,'I: Tempo Di Valse Ma Non Troppo Vivo, Quasi Moderato',180,0.99),
TRACK_TYPE(12,' II: Andante - Allegro - Norman Carol',180,0.99),
TRACK_TYPE(13,'III: Tempo Di Valse',180,0.99),
TRACK_TYPE(14,'IV: Coda: Allegro Molto Vivace',180,0.99),
TRACK_TYPE(15,'No.6 - Pas D Action: Andantino Quasi Moderato - Allegro',180,0.99),
TRACK_TYPE(16,'No.7 - Sujet',180,0.99),
TRACK_TYPE(17,'No.8 - Danse Des Coupes: Tempo Di Polacca',180,0.99),
TRACK_TYPE(18,'No.9 - Finale: Andante',180,0.99),
TRACK_TYPE(19,'No.10 - Scene: Moderato',180,0.99),
TRACK_TYPE(20,'No.11 - Scene: Allegro Moderato - Allegro Vivo',180,0.99),
TRACK_TYPE(21,'No.12 - Scene: Allegro',180,0.99),
TRACK_TYPE(22,'I: Tempo Di Valse',180,0.99),
TRACK_TYPE(23,'II: Moderato Assai - Molto Piu Mosso',180,0.99),
TRACK_TYPE(24,'III: Danses Des Cygnes: Tempo Di Valse',180,0.99),
TRACK_TYPE(25,'IV: Allegro Moderato',180,0.99),
TRACK_TYPE(26,'V: Pas D Action (Odette Et Le Prince): Andante - Andante Non Troppo - Allegro - Norman Carol',180,0.99)),
REVIEWS_TABLE(
REVIEW_TYPE(1,'Rudy Avila','Tchaikovskys Swan Lake remains a ballet favorite and a powerful star vehicle for the prima ballerina who must dance the roles of two characters- the "white swan" Odette and the black swan Odile, good and evil. Swan Lake has been recorded many times by celebrated conductors and their orchestras - Eugene Ormandy and the Philadelphia Orchestra (here its Wolfgang Sawallisch and the same orchestra from an earlier period) Canadian Charles Dutroit and the Montreal forces, Seiji Ozawa, Andre Previn and the London Symphony Orchestra, Richard Bonynge better known for his operatic vehicles with his wife Joan Sutherland, Antal Dorati and his orchestra, and even Herbert Von Karajan joined the band wagon of conducting great ballets- he conducted the complete Giselle and a concert suite of Tchaikovskys Swan Lake, Sleeping Beauty and Nutcracker. Wolfgang Sawallisch was a brilliant conductor, and unfortunately like so many conductors in Karajans time, he was underappreciated. This Swan Lake is beautifully restored and sounds fresh, powerful and lyrical. The music for Swan Lake has symphonic qualities, with a contrast of serene and jovial dances and melancholy and even fatalistic themes. The Dance of the Little Swans is bouncy and cheery, the violin solos for Odettes solo dances are almost mournful (shes mourning her swan condition/curse) and the Swan Theme is powerful and stormy, borrowed from the last notes to a Wagners Lohengrin prelude. For these reasons critics did not initially warm up to the "heavy" music of Swan Lake. But eventually it became the most beautiful of the "ballet-blancs" ever made. Other "white tutu" ballets include Giselle (Act 2 the Willis) and La Bayadere (Act 2 The Land of Shades). The music is to die for in this recording and I highly recommend it.',5.0,TO_DATE('06/07/2005', 'DD/MM/RRRR')),
REVIEW_TYPE(2,'Mateo','Herbert Von Karajan comes to mind. Slow. No sense of the arc of the entire dance, but rather a series of orchestral pieces that are played mostly mezzo forte, with limited drama and zero spontaneity. In sum, the performance fails to realize the composers intentions. I purchased the recording based on the reviews here, but will be giving it away as a gift. I may try again with Bonynges recording, which is said to be more balletic, or continue to look into the more obscure Russian recordings.', 3.0, TO_DATE('01/07/2010', 'DD/MM/RRRR')),
REVIEW_TYPE(3, 'S. Vinokurov', 'Love the CD (it has two rare favs of mine... the faster Black Swan Variation and the extended Russian Dance) however, I was shocked not to find Black Swan Pas de Deux. How can you have a COMPLETE Swan Lake recording and not include that?!?!?!',4.0, TO_DATE('31/07/2006', 'DD/MM/RRRR'))
), 1, 11.99));
