-- QUESTION 1
SELECT ALB.TITLE, ALB.RELEASE_DATE, ALB.BASE_PRICE, ART.ARTIST_NAME CONDUCTOR
FROM ALBUM ALB, ROLE R, ARTIST ART
WHERE REF(ALB) = R.ALBUM_ID
AND REF(ART) = R.ARTIST_ID
AND R.ROLE = 'Conductor'
AND REF(ALB) IN
(
  SELECT R.ALBUM_ID
  FROM ROLE R
  WHERE R.ROLE = 'Composer'
  AND R.ARTIST_ID IN
  (
    SELECT REF(ART)
    FROM ARTIST ART
    WHERE ARTIST_NAME LIKE '%Tchaikovsky'
  )
)
AND ALB.TITLE LIKE '%Swan Lake%';
/

-- QUESTION 2
CREATE OR REPLACE FUNCTION HIGH_DL_SONG
   RETURN TRACK_TYPE
IS
   trackarray TRACKS;
   total integer;
   high_dl integer :=0;
   high_dl_track TRACK_TYPE;
BEGIN
  SELECT TRACK INTO trackarray from ALBUM
     total := trackarray.count;
     FOR i in 1 .. total LOOP
        IF(trackarray(i).DL_COUNT > high_dl) THEN
          high_dl := trackarray(i).DL_COUNT;
          high_dl_track := trackarray(i);
        END IF;
     END LOOP;
  RETURN high_dl_track;
END;
/
SELECT TITLE, RELEASE_DATE, HIGH_DL_SONG.SONG_TITLE, HIGH_DL_SONG.DL_COUNT
FROM ALBUM;
/

-- QUESTION 3
SELECT ALB.TITLE, ALB.RELEASE_DATE, ALB.BASE_PRICE
FROM ALBUM ALB, ROLE R, ARTIST ART
WHERE REF(ALB) = R.ALBUM_ID
AND REF(ART) = R.ARTIST_ID
AND ALB.ALBUM_ID IN (SELECT ALBUM_ID FROM CD)
AND ALB.ALBUM_ID IN (SELECT ALBUM_ID FROM VINYL)
AND ART.ARTIST_NAME LIKE 'Bob Dylan'
GROUP BY ALB.ALBUM_ID, ALB.TITLE, ALB.RELEASE_DATE, ALB.BASE_PRICE;
/

-- QUESTION 8 - LONGEST COVER OF BLOWIN IN THE WIND
MEMBER FUNCTION FIND_ALBUM_BY_SONG RETURN BOOLEAN;
MEMBER FUNCTION GET_SONG_LENGTH RETURN NUMBER;

-- MARK ALBUMS THAT INCLUDE BLOWIN IN THE WIND
CREATE OR REPLACE TYPE BODY ALBUM_TYPE AS MEMBER FUNCTION FIND_ALBUM_BY_SONG
(P_SONG_TITLE IN VARCHAR2)
   RETURN BOOLEAN
IS
   trackarray TRACKS;
   total integer;
BEGIN
  SELECT ALB.TRACK INTO trackarray from ALBUM ALB
     total := trackarray.count;
     FOR i in 1 .. total LOOP
        IF(trackarray(i).SONG_TITLE = P_SONG_TITLE) THEN
          RETURN TRUE;
        END IF;
     END LOOP;
  RETURN FALSE;
END;
/

-- GET SONG DURATION
CREATE OR REPLACE TYPE BODY ALBUM_TYPE AS MEMBER FUNCTION GET_SONG_LENGTH
(P_SONG_TITLE IN VARCHAR2)
	RETURN NUMBER
IS
   trackarray TRACKS;
   total integer;
   high_dl integer :=0;
BEGIN
	SELECT TRACK INTO trackarray from ALBUM
	total := trackarray.count;
   FOR i in 1 .. total LOOP
   	IF(trackarray(i).SONG_TITLE = P_SONG_TITLE) THEN
      	RETURN trackarray(i).SONG_DURATION;
		END IF;
	END LOOP;
END;
/

-- LIST ALBUM REFERENCES INCLUDING BLOWIN IN THE WIND, WITH SONG DURATION
CREATE VIEW VW_LONGEST_SONG_BLOW AS
SELECT REF(ALB) ALBUM_REF, ALB.GET_SONG_LENGTH('Blowin in the Wind') SONG_LENGTH
FROM ALBUM
WHERE ALB.FIND_ALBUM_BY_SONG('Blowin in the Wind') = 1;
/

-- DISPLAY ARTIST NAME AND SONG LENGTH OF LONGEST COVER
SELECT ART.ARTIST_NAME, ALB.SONG_LENGTH
FROM ALBUM ALB, ARTIST ART, ROLE R
WHERE R.ALBUM_ID = ALB.ALBUM_REF
AND R.ARTIST_ID = REF(ART)
AND R.ROLE = 'Singer'
AND ALB.SONG_LENGTH = (SELECT MAX(SONG_LENGTH) FROM VW_LONGEST_SONG_BLOW);
