INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART989','Joe Cocker'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART990','The Moody Blues'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART991','Steve Roach'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART992','DJ Jazzy Jeff'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART994','Cick Corea'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART993','Hiromi'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART995','Arthur Lyman'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART996','Bob Dylan'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART998','Neil Young'));
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART997','Crazy Horse'));
/
INSERT INTO ARTIST VALUES(ARTIST_TYPE('ART999','Miles Davis'));
/

INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART989' AND ALB.ALBUM_ID = 'ALB986';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART989' AND ALB.ALBUM_ID = 'ALB987';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART989' AND ALB.ALBUM_ID = 'ALB988';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Band'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART990' AND ALB.ALBUM_ID = 'ALB989';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Composer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART991' AND ALB.ALBUM_ID = 'ALB990';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Rapper'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART992' AND ALB.ALBUM_ID = 'ALB991';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Piano'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART994' AND ALB.ALBUM_ID = 'ALB992';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Piano'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART994' AND ALB.ALBUM_ID = 'ALB993';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Piano'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART994' AND ALB.ALBUM_ID = 'ALB994';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Piano'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART993' AND ALB.ALBUM_ID = 'ALB994';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART995' AND ALB.ALBUM_ID = 'ALB995';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART996' AND ALB.ALBUM_ID = 'ALB996';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Singer'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART998' AND ALB.ALBUM_ID = 'ALB997';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Band'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART997' AND ALB.ALBUM_ID = 'ALB997';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Flugelhorn/Trumpet'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART999' AND ALB.ALBUM_ID = 'ALB999';
/
INSERT INTO ROLE3
	SELECT REF(ART), REF(ALB), 'Flugelhorn/Trumpet'
	FROM ARTIST ART, ALBUM3 ALB
	WHERE ART.ARTIST_ID = 'ART999' AND ALB.ALBUM_ID = 'ALB998';
/
INSERT INTO ALSO_BOUGHT3
SELECT REF(ALB1), REF(ALB2)
FROM ALBUM3 ALB1, ALBUM3 ALB2
WHERE ALB1.ALBUM_ID = 'ALB999' AND ALB2.ALBUM_ID = 'ALB998'
/