-- QUESTION 9
CREATE OR REPLACE VIEW QUESTION_9 (TITLE, RELEASE_DATE, STANDARD_PRICE) AS
SELECT ALB1.TITLE, ALB1.RELEASE_DATE, CD.PRICE FROM
ALBUM ALB1, ALBUM ALB2, ALSO_BOUGHT AB, CD
WHERE AB.ALBUM_1_ID = REF(ALB1)
AND AB.ALBUM_2_ID = REF(ALB2)
AND ALB2.ALBUM_ID = 'ALB999'
AND CD.TITLE = ALB1.TITLE
AND CD.NEW_OR_USED = 1;
UNION
SELECT ALB1.TITLE, ALB1.RELEASE_DATE, CD.PRICE FROM
ALBUM ALB1, ALBUM ALB2, ALSO_BOUGHT AB, CD
WHERE AB.ALBUM_1_ID = REF(ALB2)
AND AB.ALBUM_2_ID = REF(ALB1)
AND ALB2.TITLE = 'Sketches of Spain'
AND CD.TITLE = ALB1.TITLE
AND CD.NEW_OR_USED = 1;

--Question 5
SELECT TITLE, RELEASE_DATE FROM ALBUM WHERE TITLE LIKE '%Magnificent%';

