INSERT INTO CD3
  SELECT ALB.*, 1, 3.35
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB986';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 2.34
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB986';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 4.66
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB987';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 3.33
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB987';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 4.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 0.24
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 13.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB989';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 10.29
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB989';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 13.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB990';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 4.90
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB990';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 12.92
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB991';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 0.98
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB991';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 12.28
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB992';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 3.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB992';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 10.18
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB993';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 3.83
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB993';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 19.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB994';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 9.95
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB994';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 12.98
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB995';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 8.47
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB995';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 6.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB996';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 3.55
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB996';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 4.41
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 3.41
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 6.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB998';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 0.65
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB998';
 /
 INSERT INTO CD3
  SELECT ALB.*, 1, 14.87
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB999';
 /
 INSERT INTO CD3
  SELECT ALB.*, 0, 4.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB999';
 /
INSERT INTO VINYL3
  SELECT ALB.*, 0, 0.79
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB987';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 1, 49.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 8.00
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 1, 19.95
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB989';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 71.94
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB989';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 18.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB991';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 4.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB995';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 1,22.42
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB996';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 14.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB996';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 4.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB999';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 1, 395.12
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 1, 18.32
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB998';
 /
 INSERT INTO VINYL3
  SELECT ALB.*, 0, 15.95
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB998';
 /
INSERT INTO TAPE3
  SELECT ALB.*, 0, 9.98
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB987';
 /
INSERT INTO TAPE3
  SELECT ALB.*, 1, 39.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
  INSERT INTO TAPE3
  SELECT ALB.*, 0, 2.98
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
  INSERT INTO TAPE3
  SELECT ALB.*, 0, 6.86
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
  INSERT INTO TAPE3
  SELECT ALB.*, 1, 14.90
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
  INSERT INTO TAPE3
  SELECT ALB.*, 1, 90.38
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB999';
 /
INSERT INTO MP33
  SELECT ALB.*, 9.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB986';
 /
INSERT INTO MP33
  SELECT ALB.*, 6.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB987';
 /
INSERT INTO MP33
  SELECT ALB.*, 5.00
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB988';
 /
INSERT INTO MP33
  SELECT ALB.*, 8.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB989';
 /
INSERT INTO MP33
  SELECT ALB.*, 7.92
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB990';
 /
INSERT INTO MP33
  SELECT ALB.*, 9.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB992';
 /
INSERT INTO MP33
  SELECT ALB.*, 11.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB993';
 /
INSERT INTO MP33
  SELECT ALB.*, 18.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB994';
 /
INSERT INTO MP33
  SELECT ALB.*, 9.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB9995';
 /
INSERT INTO MP33
  SELECT ALB.*, 9.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB996';
 /
INSERT INTO MP33
  SELECT ALB.*, 9.49
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB997';
 /
INSERT INTO MP33
  SELECT ALB.*, 6.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB998';
 /
INSERT INTO MP33
  SELECT ALB.*, 14.99
  FROM ALBUM3 ALB
  WHERE ALB.ALBUM_ID = 'ALB999';
 /

 