SELECT ALB.TITLE, ALB.RELEASE_DATE, ART.ARTIST_NAME CONDUCTOR
FROM ALBUM ALB, ROLE R, ARTIST ART
WHERE REF(ALB) = R.ALBUM_ID
AND REF(ART) = R.ARTIST_ID
AND R.ROLE = 'Conductor'
AND REF(ALB) IN
(
SELECT R.ALBUM_ID
FROM ROLE R
WHERE R.ROLE = 'Composer'
AND R.ARTIST_ID IN
(
SELECT REF(ART)
FROM ARTIST ART
WHERE ARTIST_NAME LIKE '%Tchaikovsky'
)
)